services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
