services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    image: sesegma/buzzer-frontend:latest

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    image: sesegma/buzzer-server:latest
